// lib/templates/sqlite/vue/client/src/pages/List.vue
<template>
  <div>
    <h1>List Data</h1>
    <ul>
      <li v-for="item in items" :key="item.id"><strong>{{ item.name }}</strong>: {{ item.message }}</li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

interface Item { id: number; name: string; message: string }

const items = ref<Item[]>([])

onMounted(async () => {
  const res = await fetch('http://localhost:3001/api/list')
  items.value = await res.json()
})
</script>

// lib/templates/sqlite/react/client/src/pages/List.tsx
import { useEffect, useState } from 'react'

interface Item { id: number; name: string; message: string }

export default function List() {
  const [items, setItems] = useState<Item[]>([])

  useEffect(() => {
    fetch('http://localhost:3001/api/list')
      .then(res => res.json())
      .then(setItems)
  }, [])

  return (
    <div>
      <h1>List Data</h1>
      <ul>
        {items.map(item => (
          <li key={item.id}><strong>{item.name}</strong>: {item.message}</li>
        ))}
      </ul>
    </div>
  )
}
