// lib/templates/auth/clerk/vue/client/src/pages/Login.vue
<template>
  <div>
    <h1 v-if="isSignedIn">Profile</h1>
    <h1 v-else>Sign In</h1>

    <div v-if="!isLoaded">Loading...</div>

    <div v-else-if="isSignedIn && user">
      <p>Name: {{ user.fullName }}</p>
      <p>Email: {{ user.primaryEmailAddress?.emailAddress }}</p>
      <button @click="signOut">Sign Out</button>
    </div>

    <button v-else @click="signIn">Sign In with Clerk</button>
    <p v-if="!isSignedIn" style="margin-top: 1rem; font-size: 0.8rem; color: #666">Add <code>/login</code> as an Allowed Callback URL in your Clerk dashboard.</p>
  </div>
</template>

<script setup lang="ts">
import { useUser, useSignIn, useSignOut } from '@clerk/clerk-vue'

const { isLoaded, isSignedIn, user } = useUser()
const { signIn } = useSignIn()
const { signOut } = useSignOut()
</script>

// lib/templates/auth/clerk/react/client/src/pages/Login.tsx
import { useUser, SignInButton, SignOutButton } from '@clerk/clerk-react'

export default function Login() {
  const { isLoaded, isSignedIn, user } = useUser()

  if (!isLoaded) return <div>Loading...</div>

  if (isSignedIn && user) {
    return (
      <div>
        <h1>Profile</h1>
        <p>Name: {user.fullName}</p>
        <p>Email: {user.primaryEmailAddress?.emailAddress}</p>
        <SignOutButton><button>Sign Out</button></SignOutButton>
      </div>
    )
  }

  return (
    <div>
      <h1>Sign In</h1>
      <SignInButton mode="redirect"><button>Sign In with Clerk</button></SignInButton>
      <p style={{ marginTop: '1rem', fontSize: '0.8rem', color: '#666' }}>Add <code>/login</code> as an Allowed Callback URL in your Clerk dashboard.</p>
    </div>
  )
}
