// lib/templates/storage/r2/react/client/src/pages/Files.tsx
import { useEffect, useState } from 'react'

interface FileItem { key: string; size: number; url: string }

export default function Files() {
  const [files, setFiles] = useState<FileItem[]>([])

  useEffect(() => {
    fetch('http://localhost:3001/api/files')
      .then(res => res.json())
      .then(setFiles)
  }, [])

  return (
    <div>
      <h1>Files</h1>
      <ul>
        {files.map(f => (
          <li key={f.key}><a href={f.url} target="_blank" rel="noreferrer">{f.key}</a> ({f.size} bytes)</li>
        ))}
      </ul>
    </div>
  )
}

// lib/templates/storage/s3/vue/client/src/pages/Files.vue
<template>
  <div>
    <h1>Files</h1>
    <ul>
      <li v-for="f in files" :key="f.key">
        <a :href="f.url" target="_blank" rel="noreferrer">{{ f.key }}</a> ({{ f.size }} bytes)
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

interface FileItem { key: string; size: number; url: string }

const files = ref<FileItem[]>([])

onMounted(async () => {
  const res = await fetch('http://localhost:3001/api/files')
  files.value = await res.json()
})
</script>
