// lib/templates/storage/r2/react/client/src/pages/Upload.tsx
import { useState } from 'react'

export default function Upload() {
  const [file, setFile] = useState<File | null>(null)
  const [url, setUrl] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!file) return
    const form = new FormData()
    form.append('file', file)
    const res = await fetch('http://localhost:3001/api/upload', { method: 'POST', body: form })
    const data = await res.json()
    setUrl(data.url)
  }

  return (
    <div>
      <h1>Upload File</h1>
      <form onSubmit={handleSubmit}>
        <input type="file" onChange={e => setFile(e.target.files?.[0] || null)} required />
        <button type="submit">Upload</button>
      </form>
      {url && <p>Uploaded: <a href={url} target="_blank" rel="noreferrer">{url}</a></p>}
    </div>
  )
}

// lib/templates/storage/s3/vue/client/src/pages/Upload.vue
<template>
  <div>
    <h1>Upload File</h1>
    <form @submit.prevent="handleSubmit">
      <input type="file" @change="onFileChange" required />
      <button type="submit">Upload</button>
    </form>
    <p v-if="url">Uploaded: <a :href="url" target="_blank" rel="noreferrer">{{ url }}</a></p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const file = ref<File | null>(null)
const url = ref('')

function onFileChange(e: Event) {
  const input = e.target as HTMLInputElement
  file.value = input.files?.[0] || null
}

async function handleSubmit() {
  if (!file.value) return
  const form = new FormData()
  form.append('file', file.value)
  const res = await fetch('http://localhost:3001/api/upload', { method: 'POST', body: form })
  const data = await res.json()
  url.value = data.url
}
</script>
