// lib/templates/storage/r2/react/client/src/pages/Files.tsx
import { useEffect, useState } from 'react'

interface FileItem { key: string; size: number; url: string }

export default function Files() {
  const [files, setFiles] = useState<FileItem[]>([])

  useEffect(() => {
    fetch('http://localhost:3001/api/files')
      .then(res => res.json())
      .then(setFiles)
  }, [])

  return (
    <div>
      <h1>Files</h1>
      <ul>
        {files.map(f => (
          <li key={f.key}><a href={f.url} target="_blank" rel="noreferrer">{f.key}</a> ({f.size} bytes)</li>
        ))}
      </ul>
    </div>
  )
}

// lib/templates/storage/r2/solid/client/src/pages/Files.tsx
import { createSignal, onMount, For } from 'solid-js'

interface FileItem { key: string; size: number; url: string }

export default function Files() {
  const [files, setFiles] = createSignal<FileItem[]>([])

  onMount(async () => {
    const res = await fetch('http://localhost:3001/api/files')
    setFiles(await res.json())
  })

  return (
    <div>
      <h1>Files</h1>
      <ul>
        <For each={files()}>{f =>
          <li><a href={f.url} target="_blank" rel="noreferrer">{f.key}</a> ({f.size} bytes)</li>
        }</For>
      </ul>
    </div>
  )
}
