// lib/templates/auth/clerk/vue/client/src/pages/Login.vue
<template>
  <div>
    <h1 v-if="isSignedIn">Profile</h1>
    <h1 v-else>Sign In</h1>

    <div v-if="!isLoaded">Loading...</div>

    <div v-else-if="isSignedIn && user">
      <p>Name: {{ user.fullName }}</p>
      <p>Email: {{ user.primaryEmailAddress?.emailAddress }}</p>
      <button @click="signOut">Sign Out</button>
    </div>

    <button v-else @click="signIn">Sign In with Clerk</button>
    <p v-if="!isSignedIn" style="margin-top: 1rem; font-size: 0.8rem; color: #666">Add <code>/login</code> as an Allowed Callback URL in your Clerk dashboard.</p>
  </div>
</template>

<script setup lang="ts">
import { useUser, useClerk } from '@clerk/vue'

const { isLoaded, isSignedIn, user } = useUser()
const clerk = useClerk()
const signIn = () => clerk.value?.openSignIn()
const signOut = () => clerk.value?.signOut()
</script>

// lib/templates/auth/clerk/solid/client/src/pages/Login.tsx
import { createSignal, onMount } from 'solid-js'
import Clerk from '@clerk/clerk-js'

export default function Login() {
  const [user, setUser] = createSignal<any>(null)
  const [loaded, setLoaded] = createSignal(false)
  let clerk: Clerk | null = null

  onMount(async () => {
    clerk = new Clerk(import.meta.env.VITE_CLERK_PUBLISHABLE_KEY)
    await clerk.load()
    setLoaded(true)
    if (clerk.user) setUser(clerk.user as any)
  })

  const signIn = () => clerk?.openSignIn()
  const signOut = () => clerk?.signOut()

  if (!loaded()) return <div>Loading...</div>

  if (user()) {
    return (
      <div>
        <h1>Profile</h1>
        <p>Name: {user().fullName}</p>
        <button onClick={signOut}>Sign Out</button>
      </div>
    )
  }

  return (
    <div>
      <h1>Sign In</h1>
      <button onClick={signIn}>Sign In with Clerk</button>
      <p style={{ 'margin-top': '1rem', 'font-size': '0.8rem', color: '#666' }}>Add <code>/login</code> as an Allowed Callback URL in your Clerk dashboard.</p>
    </div>
  )
}
